include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true # Uncomment to disable the `avoid_print` rule
    prefer_single_quotes: true # Uncomment to enable the `prefer_single_quotes` rule
    cancel_subscriptions: true
    close_sinks: true
    prefer_final_in_for_each: true

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list

  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50

  metrics-exclude:
    - test/**

  rules:
    - avoid-unused-parameters
    - binary-expression-operand-order
    - double-literal-format
    - member-ordering
    - member-ordering-extended
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-arguments
    - no-equal-then-else
    - no-magic-number
    - no-object-declaration
    - prefer-conditional-expressions
    - prefer-trailing-comma
    - public-late-final-fields
    - private-late-final-fields
    - public-nullable-fields
    - private-nullable-fields
    - named-constructors
    - factory-constructors
    - getters
    - setters
    - public-static-methods
    - private-static-methods
    - protected-methods

    # - newline-before-return
    # - no-boolean-literal-compare
    # - no-empty-block
    # - prefer-trailing-comma
    # - prefer-conditional-expressions
    # - no-equal-then-else
