name: znar
description: A music streaming app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.4+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.1
  cached_network_image: ^3.0.0
  shared_preferences: ^2.0.5
  path_provider: ^2.0.1
  youtube_player_flutter: ^8.0.0
  # progress_dialog: ^1.2.4
  # flutter_downloader: ^1.6.0
  # color_thief_flutter: ^1.0.2
  # flutter_lyric: any
  # auto_animated: ^3.0.0
  assets_audio_player: ^3.0.3+2
  sleek_circular_slider: ^2.0.0
  miniplayer: ^1.0.0+2

  firebase_dynamic_links: ^2.0.3
  cloud_firestore: ^2.1.0

  sembast: ^3.0.1
  flutter_swiper: ^1.1.6
  path: ^1.7.0

  flutter_svg: ^0.21.0+1
  flutter_screenutil: ^3.0.0
  url_launcher: ^6.0.3
  flutter_html: any
  share: ^2.0.1
  flutter_inappwebview: ^5.2.1+1

  permission_handler: ^6.1.1
  flutter_local_notifications: ^5.0.0+1
  flutter_audio_query: ^0.3.5+6
  draggable_scrollbar: ^0.1.0
  google_fonts: ^2.0.0

  dart_tags: ^0.3.1
  dio: ^4.0.0
  device_info: ^2.0.0
  firebase_messaging: ^9.1.1

  ionicons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons:

flutter_icons:
  # android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo_y.png"

# flutter_icons:
#   android: true
#   ios: true
#   remove_alpha_ios: true
#   image_path: "assets/images/logo_y.png"
#   adaptive_icon_background: "#FF111111"
#   adaptive_icon_foreground: "assets/images/logo_y.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Kefa
      fonts:
        - asset: assets/fonts/Kefa.ttc
    - family: Didot
      fonts:
        - asset: assets/fonts/Didot.ttc
    - family: AvenirNext
      fonts:
        - asset: assets/fonts/AvenirNext/Metropolis-Regular.otf
        - asset: assets/fonts/AvenirNext/Metropolis-Thin.otf
          weight: 100
        - asset: assets/fonts/AvenirNext/Metropolis-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/AvenirNext/Metropolis-Light.otf
          weight: 300
        - asset: assets/fonts/AvenirNext/Metropolis-Medium.otf
          weight: 500
        - asset: assets/fonts/AvenirNext/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/AvenirNext/Metropolis-Bold.otf
          weight: 700
        - asset: assets/fonts/AvenirNext/Metropolis-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/AvenirNext/Metropolis-Black.otf
          weight: 900
