// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd4A0gr1l8Vm7nCbqaGLGAzSkSs_ui9Rc',
    appId: '1:514591476510:web:e8105c7e23b182ee0f570f',
    messagingSenderId: '514591476510',
    projectId: 'znar-70fab',
    authDomain: 'znar-70fab.firebaseapp.com',
    storageBucket: 'znar-70fab.appspot.com',
    measurementId: 'G-C0LPC00FWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnvHCrLfhMmuQmvzy5rhAZqODVZDb9pzk',
    appId: '1:514591476510:android:5b39bec3548264ef0f570f',
    messagingSenderId: '514591476510',
    projectId: 'znar-70fab',
    storageBucket: 'znar-70fab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4gJqyAC-zI5NejX8YvpzkwGhRJCLhJCM',
    appId: '1:514591476510:ios:e7af0c7d0c8e35600f570f',
    messagingSenderId: '514591476510',
    projectId: 'znar-70fab',
    storageBucket: 'znar-70fab.appspot.com',
    androidClientId: '514591476510-3u8pchmq9sv9n7j39ie5l7ou7dhpnjpa.apps.googleusercontent.com',
    iosClientId: '514591476510-0bvq4o0gtcsv9rm3fn1ptihhaqb9im89.apps.googleusercontent.com',
    iosBundleId: 'music.streaming.znar',
  );
}
