class Language {
  static const Map<String, String> ENGLISH = {
    // 'explore': 'Explore',
    'discover': 'Discover',
    'songs': 'Songs',
    'song': 'Song',
    'play': 'Play',

    'lyric': 'Lyric',
    'albums': 'Albums',
    'album': 'Album',
    'go_to': 'Go to',
    'artists': 'Artists',
    'artist': 'Artist',
    'music_video': 'Music Video',
    'music_videos': 'Music Videos',
    'video': 'Video',
    'videos': 'Videos',
    'other_videos': 'Other Music Videos',
    'youtube_channels': 'YouTube Channels',
    'channel': 'Channel',
    'playlists': 'Playlists',
    'playlists_nav': 'Playlists',
    'playlist': 'Playlist',
    'similar_from_artist': 'Similar from artist',
    'local_playlists': 'My Playlist',
    'online_playlists': 'Charts',
    'playlist_deleted': 'Playlist deleted',
    'create_playlist': 'Create playlist',
    'please_write_title': 'Please write a title',
    'create_playlist_failed': 'Failed to create playlist, Please try again ',
    'create_playlist_success': 'Playlist successfully created',
    'view_all': 'View All',
    'more': 'More',
    'share': 'Share',
    'remove': 'Remove',
    'add_to_playlist': 'Add to playlist',
    'song_added': 'Song added',
    'failed_song_added': 'Failed to add to playlist',
    'popular_playlists': 'Popular Playlists',
    'trending_playlists': 'Trending Playlists',
    'popular_songs': 'Popular Songs',
    'timeless_songs': 'Timeless Songs',
    'hit_albums': 'Hit Albums',
    'popular_artists': 'Popular Artists',
    'setting': 'Setting',
    'learn_more': 'Learn More',
    'offline': 'Offline',
    'charts': 'Charts',
    'search': 'Search',
    'search_album': 'Album title...',
    'search_song': 'Song title...',
    'search_artist': 'Artist title...',
    'search_video': 'Music Video title...',
    'search_playlist': 'Playlist title...',
    'search_sth': 'Search...',
    'download': 'Download',
    'downloaded': 'Downloaded',
    'downloaded_songs': 'Downloads',
    'langauge_changed': 'Language has changed',
  };
  // static const Map<String, String> AMHARIC = {
  // 'explore': 'ሁሉ',
  //   'discover': 'Discover',
  //   'songs': 'ዘፈኖች',
  //   'song': 'ዘፈን',
  // 'play': 'Play',
  // 'lyric':'Lyric',
  //   'albums': 'አልበሞች',
  //   'album': 'አልበም',
  //   'go_to': 'Go to',
  //   'artists': 'አርቲስቶች',
  //   'artist': 'አርቲስት',
  //   'music_video': 'ሙዚቃ ቪድዮ',
  //   'music_videos': 'ሙዚቃ ቪድዮዎች',
  //   'video': 'ቪድዮ',
  //   'videos': 'ቪድዮዎች',
  // 'other_videos': 'Other Music Videos',
  //   'youtube_channels': 'ዩትዩብ ቻናሎች',
  //   'channel': 'ቻናል',
  //   'playlists': 'የዘፈኖች ዝርዝር',
  //   'playlists_nav': 'የዘፈኖች ዝርዝር',
  //   'playlist': 'የዘፈኖች ዝርዝር',
  //   'similar_from_artist': 'ከአርቲስቱ',
  //   'local_playlists': 'Local',
  //   'online_playlists': 'Online',
  //   'playlist_deleted': 'የዘፈኖቹ ዝርዝር ጠፍቷል',
  //   'create_playlist': 'የዘፈኖች ዝርዝር ፍጠር',
  //   'please_write_title': 'እባክዎን አርእስቱን ይፃፉ',
  //   'create_playlist_failed': 'ትእዛዝዎን አልተሳካም፣ አባክዎን አንደገና ይሞክሩ',
  //   'create_playlist_success': 'ትእዛዝዎን ተሳክቷል',
  //   'view_all': 'ተጨማሪ',
  //   'more': 'More',
  //   'share': 'ያጋሩ',
  //   'remove': 'ይጥፋ',
  //   'add_to_playlist': 'ወደ ፕለይሊስት አስገባ',
  //   'song_added': 'ዘፈኑ ተጨምሯል',
  //   'failed_song_added': 'አልተሳካም',
  //   'popular_playlists': 'ምርጥ የዘፈኖች ዝርዝር',
  //   'trending_playlists': 'Trending Playlists',
  //   'popular_songs': 'ተወዳጅ ዘፈኖች',
  //   'timeless_songs': 'Timeless Songs',
  //   'hit_albums': 'ምርጥ አልበሞች',
  //   'popular_artists': 'ተወዳጅ ኣርቲስቶች',
  //   'setting': 'ቅንብሮች',
  //   'learn_more': 'ለበጠ መረጃ',
  //   'offline': 'Offline',
  //   'charts': 'Charts',
  // 'search': 'Search',
  //   'search_album': 'አልበም ፈልግ...',
  //   'search_song': 'ዘፈን ፈልግ...',
  //   'search_artist': 'አርቲስት ፈልግ...',
  //   'search_video': 'ቪድዮ ፈልግ...',
  //   'search_playlist': 'ፕለይሊስት ፈልግ...',
  //   'search_sth': 'ፈልግ...',
  //   'download': 'አውርድ',
  //   'downloaded': 'Downloaded',
  //   'downloaded_songs': 'የወረዱ',
  //   'langauge_changed': 'ቋንቋ ተቀይሯል',
  // };
  static const Map<String, String> TIGRIGNA = {
    // 'explore': 'ኹሉ',
    'discover': 'ዳህሳስ',
    'songs': 'ደርፍታት',
    'song': 'ደርፊ',
    'play': 'ተፃወት',
    'lyric': 'ግጥሚ',
    'albums': 'ኣልበማት',
    'album': 'ኣልበም',
    'go_to': 'Go to',
    'artists': 'ኣርቲስታት',
    'artist': 'አርቲስት',
    'music_video': 'ቪድዮ ሙዚቃ',
    'music_videos': 'ቪድዮታት ሙዚቃ',
    'video': 'ቪድዮ',
    'videos': 'ቪድዮታት',
    'other_videos': 'ካልኦት ቪድዮታት',
    'youtube_channels': 'ዩትዩብ ቻናላት',
    'channel': 'ቻናል',
    'playlists': 'ዝርዝር ደርፍታት',
    'playlists_nav': 'ዝርዝር',
    'playlist': 'ናይ ደርፍታት ዝርዝር',
    'similar_from_artist': ' ካብ\'ቲ አርቲስት',
    'local_playlists': 'Local',
    'online_playlists': 'Online',
    'playlist_deleted': 'የዘፈኖቹ ዝርዝር ጠፍቷል',
    'create_playlist': 'የዘፈኖች ዝርዝር ፍጠር',
    'please_write_title': 'እባክዎን አርእስቱን ይፃፉ',
    'create_playlist_failed': 'ትእዛዝዎን አልተሳካም፣ አባክዎን አንደገና ይሞክሩ',
    'create_playlist_success': 'ትእዛዝዎን ተሳክቷል',
    'view_all': 'ኩሉ',
    'more': 'ተወሳኺ',
    'share': 'ነካፍል',
    'remove': 'ይጥፋ',
    'add_to_playlist': 'ወደ ፕለይሊስት አስገባ',
    'song_added': 'ዘፈኑ ተጨምሯል',
    'failed_song_added': 'አልተሳካም',
    'popular_playlists': 'ናይ ደርፍታት ዝርዝር',
    'trending_playlists': 'Trending Playlists',
    'popular_songs': 'ተወዳጅ ዘፈኖች',
    'timeless_songs': 'ዘመን ተሻገርቲ',
    'hit_albums': 'ምርጥ አልበሞች',
    'popular_artists': 'ተወዳጅ ኣርቲስቶች',
    'setting': 'ቅንብሮች',
    'learn_more': 'ለበጠ መረጃ',
    'offline': 'Offline',
    'charts': 'Charts',
    'search': 'ድልያ',
    'search_album': 'አልበም ፈልግ...',
    'search_song': 'ዘፈን ፈልግ...',
    'search_artist': 'አርቲስት ፈልግ...',
    'search_video': 'ቪድዮ ፈልግ...',
    'search_playlist': 'ፕለይሊስት ፈልግ...',
    'search_sth': 'ፈልግ...',
    'download': 'አውርድ',
    'downloaded': 'Downloaded',
    'downloaded_songs': 'የወረዱ',
    'langauge_changed': 'ቋንቋ ተቀይሩ',
  };

  static String locale(String lang, String key) {
    switch (lang) {
      case 'en':
        return ENGLISH[key];
      case 'am':
      // return AMHARIC[key];
      case 'tg':
        return TIGRIGNA[key];
      default:
        return TIGRIGNA[key];
    }
  }
}
